import type { Metadata, Viewport } from "next";
import { Kapakana } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { SiteLayout } from "~/app/components/primary-layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-sans",
});

const kapakana = Kapakana({
  variable: "--font-script",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${kapakana.variable}`}>
        <SiteLayout>{children}</SiteLayout>
      </body>
    </html>
  );
}
